name: 'JUnit Report Action'
description: 'Report JUnit test results as annotations on Github Pull Request [junit]'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'Specify the token to use to publish the check.'
    required: false
    default: ${{ github.token }}
  github_token:
    description: 'Deprecated syntax to specify github token.'
    required: true
  report_paths:
    description: 'Xml report paths in glob format'
    required: false
    default: '**/junit-reports/TEST-*.xml'
  exclude_sources:
    description: 'Comma seperated list of source folders to ignore for lookup'
    required: false
    default: '/build/,/__pycache__/'
  suite_regex:
    description: 'Regular expression for the named test suites'
    required: false
    default: ''
  update_check:
    description: 'Defines if the active check should be updated instead'
    required: false
    default: 'false'
  check_name:
    description: 'Check name for test reports.'
    required: false
    default: 'JUnit Test Report'
  commit:
    description: 'Commit SHA to update the check status.'
    required: false
  fail_on_failure:
    description: 'Fail the build in case a test failure occurred.'
    required: false
    default: 'false'
  require_tests:
    description: 'Fail if no test are found.'
    required: false
    default: 'false'
  include_passed:
    description: 'Include passed tests in the report'
    required: false
    default: 'false'
  summary:
    description: 'Additional text to summary output'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
