name: 'CI'
on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    if: github.event_name  == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Test JUnit test import
        uses: ./
        if: endsWith(github.ref, 'main') == false
        with:
          check_name: Example JUnit Test Report
          report_paths: '**/surefire-reports/TEST-*.xml'
          summary: '<table><thead><tr><th> Application (src/applications) </th></tr></thead><tbody><tr><td> test </td></tr></tbody></table>'
      - name: Test PyTest test import
        uses: ./
        if: endsWith(github.ref, 'main') == false
        with:
          check_name: Example Pytest Report
          report_paths: test_results/python/report.xml
          include_passed: true
      - name: Install NPM
        run: |
          npm install
      - name: Run NPM
        run: |
          npm run all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/config/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@6034af24fba4e5a8e975aaa6056554efe4c794d0
        with:
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          